
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 29 13:28:36 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LPARENT = 26;
  public static final int RPARENT = 27;
  public static final int LBRACKET = 24;
  public static final int CHAR = 50;
  public static final int CONST = 8;
  public static final int YIELD = 47;
  public static final int CASE = 21;
  public static final int GREATER = 33;
  public static final int SEMI = 14;
  public static final int CONTINUE = 19;
  public static final int MINUS = 37;
  public static final int LESS = 35;
  public static final int AND = 41;
  public static final int RECORD = 10;
  public static final int OR = 42;
  public static final int BOOL = 51;
  public static final int COMMA = 16;
  public static final int CLASS = 9;
  public static final int INC = 44;
  public static final int DIV = 39;
  public static final int PLUS = 36;
  public static final int IF = 53;
  public static final int ASSIGN = 43;
  public static final int LESSEQ = 34;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 25;
  public static final int EQUAL = 30;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 38;
  public static final int NUMBER = 49;
  public static final int MOD = 40;
  public static final int IDENT = 52;
  public static final int BREAK = 3;
  public static final int VOID = 18;
  public static final int SWITCH = 20;
  public static final int COLON = 28;
  public static final int ELSE = 54;
  public static final int LBRACE = 22;
  public static final int ENUM = 4;
  public static final int READ = 12;
  public static final int GOTO = 13;
  public static final int WHILE = 6;
  public static final int RBRACE = 23;
  public static final int EXTENDS = 11;
  public static final int GREATEREQ = 32;
  public static final int QUESTION = 29;
  public static final int DEC = 45;
  public static final int SWAP = 48;
  public static final int PRINT = 17;
  public static final int DO = 5;
  public static final int NOTEQ = 31;
}

