
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 15 12:28:20 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LPARENT = 24;
  public static final int RPARENT = 25;
  public static final int LBRACKET = 22;
  public static final int CHAR = 48;
  public static final int CONST = 8;
  public static final int YIELD = 45;
  public static final int CASE = 19;
  public static final int GREATER = 31;
  public static final int SEMI = 12;
  public static final int CONTINUE = 17;
  public static final int MINUS = 35;
  public static final int LESS = 33;
  public static final int AND = 39;
  public static final int OR = 40;
  public static final int BOOL = 49;
  public static final int COMMA = 14;
  public static final int CLASS = 9;
  public static final int INC = 42;
  public static final int DIV = 37;
  public static final int PLUS = 34;
  public static final int IF = 51;
  public static final int ASSIGN = 41;
  public static final int LESSEQ = 32;
  public static final int DOT = 44;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 23;
  public static final int EQUAL = 28;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 36;
  public static final int NUMBER = 47;
  public static final int MOD = 38;
  public static final int IDENT = 50;
  public static final int BREAK = 3;
  public static final int VOID = 16;
  public static final int SWITCH = 18;
  public static final int COLON = 26;
  public static final int ELSE = 52;
  public static final int LBRACE = 20;
  public static final int ENUM = 4;
  public static final int READ = 11;
  public static final int WHILE = 6;
  public static final int RBRACE = 21;
  public static final int EXTENDS = 10;
  public static final int GREATEREQ = 30;
  public static final int QUESTION = 27;
  public static final int DEC = 43;
  public static final int SWAP = 46;
  public static final int PRINT = 15;
  public static final int DO = 5;
  public static final int NOTEQ = 29;
}

